on:
  push:
  pull_request:
    branches: [master]
  schedule:
    - cron: '0 6 * * 6'
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        crystal: [0.36.1, latest, nightly]
    runs-on: ubuntu-latest
    steps:
      - name: Download source
        uses: actions/checkout@v2
      - name: Install Crystal
        uses: oprypin/install-crystal@v1
        with:
          crystal: ${{ matrix.crystal }}
      - name: Run tests
        run: crystal spec
      - name: Check formatting
        run: crystal tool format --check
        if: matrix.crystal == 'latest'